### ISSUE TITLE
Segfault when changing the ruleset with an existing world and database

### ISSUE THREAD

**Issue by NetSysFire** [worldforge/cyphesis#32]
### Steps to reproduce:

1. Use the demo worlds, use deeds as the ruleset.
2. Register an account and go play around a bit.
3. Shutdown cyphesis, change `/etc/cyphesis/cyphesis.vconf` to use `ruleset="mason"` and `autoimport="/usr/share/worldforge/worlds/mason/moraf/world.xml"`
4. Start cyphesis again.
5. Immediate segfault.

Important stdout/stderr which is not in the trace:

```
2022-07-15T01:22:12 ERROR Rule database table contains no rules.
2022-07-15T01:22:12 INFO Looking for extra python scripts in "/var/lib/cyphesis/.local/share/cyphesis/cyphesis.d".
2022-07-15T01:22:12 INFO Restoring world from database...
2022-07-15T01:22:12 INFO Starting restoring world from storage.
2022-07-15T01:22:12 ERROR Could not restore entity with id 7 of type thing, most likely caused by this type missing.
2022-07-15T01:22:12 ERROR Could not restore entity with id 8 of type land, most likely caused by this type missing.
cyphesis: /home/build/worldforge/cyphesis/src/cyphesis/src/server/StorageManager.cpp:186: void StorageManager::restorePropertiesRecursively(LocatedEntity&): Assertion `ent.getType() != nullptr' failed.
```

Trace: [gdb.txt](https://github.com/worldforge/cyphesis/files/9116557/gdb.txt)

### Expected behavior:

Something that says "Fatal: Entities present were created by a ruleset which is not the one running. Clear <in whatever file these entities are stored> and try again." instead of segfaulting.

**Comment by erikogenvik** [comment]
This is not a segfault (SIGSEGV) but instead an "abort" (SIGABRT) signal.
An "abort" signal is emitted if asserts fail, which happens here. 
Asserts are only enabled when compiled in debug mode.

What you describe is however totally correct. This should not be an assertion check, it should be a more thorough check that the data being restored is valid, with a exception thrown if there are types missing, along with better error messages.

**Comment by erikogenvik** [comment]
Fixed here: https://github.com/worldforge/cyphesis/commit/6be2147bea9fc3a731b4cee9c913ea6d8a092ca1
